---
- hosts: all
  become: yes
  tasks:
    - name: Create project directory
      file:
        path: /home/vagrant/project
        state: directory
        owner: vagrant
        group: vagrant

    - name: Copy Docker Compose file
      copy:
        src: /vagrant/docker-compose.yml
        dest: /home/vagrant/project/docker-compose.yml
        owner: vagrant
        group: vagrant

    - name: Copy web files
      copy:
        src: "{{ item }}"
        dest: "/home/vagrant/project/{{ item }}"
        owner: vagrant
        group: vagrant
      loop:
        - index1.html
        - index2.html
        - nginx.conf

    - name: Deploy Docker Compose stack
      docker_compose:
        project_src: /home/vagrant/project
        state: present

    - name: Restart Docker containers
      docker_compose:
        project_src: /home/vagrant/project
        state: present
        restarted: yes

    - name: Wait for services to start
      wait_for:
        host: localhost
        port: 80
        timeout: 60

    # - name: Test web services
    #   uri:
    #     url: "http://localhost{{ item }}"
    #     return_content: yes
    #   register: webpage
    #   loop:
    #     - /web1/
    #     - /web2/

    # - name: Display web page content
    #   debug:
    #     var: webpage
    - name: Test web services
      uri:
        url: "http://localhost{{ item }}"
        return_content: yes
      register: webpage
      loop:
        - ""
        - "/web1/"
        - "/web2/"
      retries: 3
      delay: 5
      until: webpage.status == 200

    - name: Display web page content
      debug:
        var: webpage.results